/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3nqHduFDcGM
 */
import { Input } from "@/components/ui/input";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Label } from "@/components/ui/label";
import { client } from "@/lib/hc";
import { unstable_noStore as noStore } from "next/cache";
import { P, match } from "ts-pattern";
import { Suspense } from "react";
import { SavedTweetsSkeleton } from "./saved-tweets-skeleton";
import { SavedTweetFilters } from "./saved-tweet-filters";
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "./ui/pagination";
import { usePathname } from "next/navigation";
import { SavedTweetPaginationFooter } from "./saved-tweet-pagination-footer";

function TweetItem({
  tweet,
}: {
  tweet: {
    content: string;
    tweetId: string;
    author_username: string;
    createdAt: string;
    isThread?: boolean | null | undefined;
    threadId?: string | null | undefined;
    replyToTweetId?: string | null | undefined;
  };
}) {
  return (
    <div className="flex items-start gap-4">
      <div className="flex-shrink-0">
        <Avatar className="w-12 h-12">
          <AvatarImage alt="@johndoe" src="/placeholder-avatar.jpg" />
          <AvatarFallback>AC</AvatarFallback>
        </Avatar>
      </div>
      <div className="border rounded-lg p-4 w-full">
        <p className="text-lg font-medium">{tweet.author_username}</p>
        <p className="text-gray-600">@{tweet.author_username}</p>
        <p>{tweet.content}</p>
      </div>
    </div>
  );
}

async function SavedTweetResults({
  params,
}: {
  params: { search?: string; page?: number; limit?: number };
}) {
  noStore();

  const res = await client.tweet.v1.$get({
    query: {
      limit: params.limit || 10,
      page: params.page || 1,
      ...(params.search ? { author_username: `$like:${params.search}` } : {}),
    },
  });

  const data = await res.json();
  return match(data)
    .with(
      {
        data: P.nonNullable,
      },
      ({ data }) => {
        return Array.isArray(data.docs) && data.docs.length > 0 ? (
          <div className="flex flex-col gap-4">
            {data.docs.map((tweet) => (
              <TweetItem key={tweet.tweetId} tweet={tweet} />
            ))}
            <div className="flex justify-center items-center">
              <SavedTweetPaginationFooter
                totalPages={
                  params.limit
                    ? Math.ceil(data.total / Number(params.limit))
                    : Math.ceil(data.total / 10)
                }
                currentPage={Number(params.page) || 1}
              />
            </div>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center">
            <div className="w-full max-w-5xl">
              <div className="flex flex-col items-center justify-center gap-2 text-center">
                <h1 className="text-2xl text-center font-semibold mb-4">
                  No results found
                </h1>
                <p className="text-xl text-muted-foreground sm:text-2xl">
                  Try a different search term.
                </p>
              </div>
            </div>
          </div>
        );
      }
    )
    .with(
      {
        error: P.nonNullable,
      },
      ({ error }) => {
        return (
          <p className="text-center text-sm text-muted-foreground">{error}</p>
        );
      }
    )
    .exhaustive();
}

function createUniqueKeyFromParams(params: {
  search?: string;
  page?: number;
  limit?: number;
}) {
  const defaultKey = "default-saved-tweets-list";
  const defaultPage = 1;
  const defaultLimit = 10;
  return `${params.search || defaultKey}-${params.page || defaultPage}-${
    params.limit || defaultLimit
  }`;
}

export function SavedTweets({
  params,
}: {
  params: { search?: string; page?: number; limit?: number };
}) {
  return (
    <section key="1" className="flex flex-1 flex-col gap-4 p-6">
      <div className="flex items-center justify-between flex-col">
        <h1 className="text-2xl text-center font-semibold mb-4">
          Tweets Saved
        </h1>
        <p className="text-center text-sm text-muted-foreground">
          These are the tweets you have saved in your collection.
        </p>
      </div>
      <SavedTweetFilters />
      <div className="border rounded-lg p-6 flex flex-col gap-6">
        <Suspense
          fallback={<SavedTweetsSkeleton />}
          // This is a hack to make the component re-render the fallback when the search param changes,
          // otherwise the fallback will not re-render when the search param changes (this works perfectly fine but doesn't give any feedback to the user)
          key={createUniqueKeyFromParams(params)}
        >
          <SavedTweetResults params={params} />
        </Suspense>

        <div className="grid grid-cols-1 gap-4"></div>
        {/* <div className="border-t pt-4">
          <h2 className="text-lg font-semibold mb-2">Add tweet</h2>
          <p className="text-sm text-gray-600 mb-4">
            Add a new tweet to your collection.
          </p>
          <div className="flex flex-col space-y-4">
            <div>
              <Label htmlFor="tweet-url">URL</Label>
              <Input
                id="tweet-url"
                placeholder="Add a link to your website, blog, or social media profile."
              />
            </div>
            <div className="flex space-x-2">
              <Button>Add tweet</Button>
              <Button variant="outline">Reset form</Button>
            </div>
          </div>
        </div> */}
      </div>
    </section>
  );
}
